name: Generate Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente
  workflow_dispatch:  # Permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Stats
        uses: jstrieb/github-stats@master
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
